### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by zeroxoneafour** [MercuryWorkshop/epoxy-tls#5]
I would like to fork and use only the server part of this project for a cleaned up cloud deployed app that I am making. As of right now, there is no license and as such there is an implied copyright that means I cannot use the source code in another open source application.

I don't care how permissive the license is because my project will also be open source.

**Comment by FoxMoss** [comment]
i mean we could just give you non transferable rights to modify and distribute the codebase. the entire repo doesnt need to be licensed.

**Comment by zeroxoneafour** [comment]
That would also work. I assume it would hold up legally even if my repo was forked without modification by other users in the case that replit bans my repo specifically from being hosted.

My repository is at https://github.com/corn-unblocked/cornng-backend-wisp. Its made up of the rust wisp server with a few modifications to run on rust stable. I guess as of now I have the right to distribute the code; if not, I can probably still take it down.

**Comment by r58Playz** [comment]
epoxy-server is now licensed as AGPL. Please update your repo's license.
